# Generated by Django 4.1.7 on 2023-03-16 05:57

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrum", "0003_alter_scrumboard_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["name"]
            ),
        ),
        migrations.AddField(
            model_name="scrumboard",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["name"]
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["name"]
            ),
        ),
    ]
