# Generated by Django 4.1.7 on 2023-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrum", "0004_project_slug_scrumboard_slug_task_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("NA", "Not Assigned"),
                    ("IP", "In Progress"),
                    ("CP", "Completed"),
                ],
                default="NA",
                max_length=20,
            ),
        ),
    ]
