# Generated by Django 4.1.7 on 2023-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrum", "0005_alter_task_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("NA", "Not Assigned"),
                    ("TD", "To Do"),
                    ("IP", "In Progress"),
                    ("CP", "Completed"),
                ],
                default="NA",
                max_length=20,
            ),
        ),
    ]
